import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Calendar, 
  AlertTriangle, 
  Activity, 
  ChevronDown, 
  ClipboardCheck, 
  ShieldAlert,
  Inbox,
  Sparkles
} from "lucide-react";
import MainLayout from "../layouts/MainLayout";
import { getDetections } from "../services/detectionService.js";

function DetectionHistory() {
  const [detections, setDetections] = useState([]);
  const [loading, setLoading] = useState(true);
  const [expandedCard, setExpandedCard] = useState(null);

  useEffect(() => {
    loadDetections();
  }, []);

  const loadDetections = async () => {
    try {
      setLoading(true);
      const data = await getDetections();
      setDetections(data);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const toggleExpand = (id) => {
    setExpandedCard(expandedCard === id ? null : id);
  };

  const getSeverityStyles = (severity) => {
    const status = severity?.toLowerCase() || "";
    if (status.includes("high") || status.includes("severe")) {
      return "bg-red-50 text-red-700 border-red-200";
    }
    if (status.includes("medium") || status.includes("moderate")) {
      return "bg-amber-50 text-amber-700 border-amber-200";
    }
    return "bg-green-50 text-green-700 border-green-200";
  };

  // Modern Skeleton Loading Screen
  if (loading) {
    return (
      <MainLayout>
        <div className="max-w-5xl mx-auto px-6 py-12 animate-pulse">
          <div className="h-10 bg-zinc-200 rounded-lg w-64 mb-2"></div>
          <div className="h-5 bg-zinc-200 rounded-lg w-80 mb-10"></div>
          <div className="space-y-4">
            {[1, 2, 3].map((n) => (
              <div key={n} className="h-20 bg-zinc-100 rounded-2xl"></div>
            ))}
          </div>
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <div className="bg-zinc-50/50 min-h-screen py-12">
        <div className="max-w-5xl mx-auto px-6">
          
          {/* Header Section */}
          <div className="mb-10">
            <h1 className="text-4xl font-black text-zinc-900 tracking-tight">
              Scan Logs & History
            </h1>
            <p className="text-zinc-500 font-medium mt-1">
              Review and manage past crop diagnostic evaluations generated by Gemini Vision AI.
            </p>
          </div>

          {detections.length === 0 ? (
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white border border-zinc-200 rounded-3xl p-12 text-center shadow-sm max-w-md mx-auto"
            >
              <div className="w-16 h-16 bg-zinc-50 text-zinc-400 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Inbox className="w-8 h-8" />
              </div>
              <h2 className="text-xl font-bold text-zinc-800">No logs on record</h2>
              <p className="text-zinc-500 text-sm mt-1">
                You haven't run any AI plant health diagnostics yet.
              </p>
            </motion.div>
          ) : (
            <div className="space-y-4">
              {detections.map((item, index) => {
                const isExpanded = expandedCard === item._id;
                
                return (
                  <motion.div
                    key={item._id}
                    initial={{ opacity: 0, y: 15 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="bg-white border border-zinc-200/80 rounded-2xl shadow-sm overflow-hidden hover:border-zinc-300 transition-colors"
                  >
                    {/* Collapsible Trigger Accordion Header Area */}
                    <div 
                      onClick={() => toggleExpand(item._id)}
                      className="p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 cursor-pointer select-none bg-white hover:bg-zinc-50/60 transition-colors"
                    >
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded-xl bg-green-50 text-green-600 flex items-center justify-center font-bold text-xl flex-shrink-0">
                          🌿
                        </div>
                        <div>
                          <h2 className="text-xl font-bold text-zinc-800 tracking-tight">
                            {item.disease}
                          </h2>
                          <div className="flex items-center gap-3 text-xs font-semibold text-zinc-400 mt-0.5">
                            <span className="flex items-center gap-1">
                              <Calendar className="w-3.5 h-3.5" /> 
                              {new Date(item.createdAt).toLocaleDateString(undefined, {
                                month: "short",
                                day: "numeric",
                                year: "numeric"
                              })}
                            </span>
                            <span>•</span>
                            <span>{new Date(item.createdAt).toLocaleTimeString(undefined, {
                              hour: '2-digit',
                              minute:'2-digit'
                            })}</span>
                          </div>
                        </div>
                      </div>

                      {/* Header Actions Area (Severity Flag + Drop Toggle Arrow) */}
                      <div className="flex items-center justify-between sm:justify-end gap-4 border-t sm:border-0 pt-3 sm:pt-0 border-zinc-100">
                        <span className={`inline-flex items-center gap-1 px-3 py-1 border rounded-full text-xs font-bold uppercase tracking-wider ${getSeverityStyles(item.severity)}`}>
                          <AlertTriangle className="w-3 h-3" /> {item.severity}
                        </span>

                        <motion.div
                          animate={{ rotate: isExpanded ? 180 : 0 }}
                          transition={{ type: "spring", stiffness: 200, damping: 20 }}
                          className="w-8 h-8 rounded-lg bg-zinc-100 text-zinc-500 flex items-center justify-center"
                        >
                          <ChevronDown className="w-4 h-4" />
                        </motion.div>
                      </div>
                    </div>

                    {/* Smooth Nested Dropdown Body Container Panel */}
                    <AnimatePresence initial={false}>
                      {isExpanded && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: "auto", opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.25, ease: "easeInOut" }}
                        >
                          <div className="px-5 pb-6 border-t border-zinc-100 bg-zinc-50/30 grid md:grid-cols-3 gap-6 pt-6">
                            
                            {/* Column 1: Observed Symptoms */}
                            <div className="md:col-span-1">
                              <h3 className="font-bold text-zinc-800 text-sm tracking-wide uppercase flex items-center gap-1.5 mb-3 text-zinc-400">
                                <Activity className="w-4 h-4 text-green-600" /> Symptoms
                              </h3>
                              {item.symptoms && item.symptoms.length > 0 ? (
                                <ul className="space-y-1.5">
                                  {item.symptoms.map((symptom, idx) => (
                                    <li key={idx} className="text-sm text-zinc-600 bg-white border border-zinc-200/60 px-3 py-2 rounded-xl flex items-center gap-2">
                                      <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 flex-shrink-0" />
                                      <span>{symptom}</span>
                                    </li>
                                  ))}
                                </ul>
                              ) : (
                                <p className="text-xs text-zinc-400 italic">No direct symptoms listed.</p>
                              )}
                            </div>

                            {/* Column 2: Prescribed Treatment Blueprint */}
                            <div className="md:col-span-1">
                              <h3 className="font-bold text-zinc-800 text-sm tracking-wide uppercase flex items-center gap-1.5 mb-3 text-zinc-400">
                                <ClipboardCheck className="w-4 h-4 text-emerald-600" /> Treatment Plan
                              </h3>
                              <div className="text-sm text-zinc-600 bg-white border border-zinc-200/60 p-4 rounded-xl leading-relaxed shadow-sm">
                                {item.treatment}
                              </div>
                            </div>

                            {/* Column 3: Recommended Marketplace Products */}
                            <div className="md:col-span-1">
                              <h3 className="font-bold text-zinc-800 text-sm tracking-wide uppercase flex items-center gap-1.5 mb-3 text-zinc-400">
                                <Sparkles className="w-4 h-4 text-yellow-500 fill-yellow-500" /> Care Products
                              </h3>
                              {item.recommendedProducts && item.recommendedProducts.length > 0 ? (
                                <ul className="space-y-1.5">
                                  {item.recommendedProducts.map((product, idx) => (
                                    <li key={idx} className="text-sm font-semibold text-green-700 bg-green-50/40 border border-green-600/10 px-3 py-2.5 rounded-xl flex items-center gap-2.5">
                                      <span>📦</span>
                                      <span>{product}</span>
                                    </li>
                                  ))}
                                </ul>
                              ) : (
                                <p className="text-xs text-zinc-400 italic">No targeted cross-sell items recommended.</p>
                              )}
                            </div>

                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>

                  </motion.div>
                );
              })}
            </div>
          )}

        </div>
      </div>
    </MainLayout>
  );
}

export default DetectionHistory;